export * from "./Home";
export * from "./Ginuwa";
export * from "./History";
export * from "./Royal";
export * from "./Warri";
export * from "./Account";
export * from "./Event";
export * from "./Speech";
export * from "./Press";